apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shepherd.fullname" . }}-secret
  labels:
    {{- include "shepherd.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.app.secrets.secretKey | b64enc | quote }}
  {{- if .Values.app.secrets.webhookSecret }}
  webhook-secret: {{ .Values.app.secrets.webhookSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.external.enabled }}
  mongodb-uri: {{ include "shepherd.mongodbConnectionString" . | b64enc | quote }}
  mongodb-username: {{ .Values.mongodb.external.username | b64enc | quote }}
  mongodb-password: {{ .Values.mongodb.external.password | b64enc | quote }}
  mongodb-database: {{ .Values.mongodb.external.database | b64enc | quote }}
  mongodb-auth-source: {{ .Values.mongodb.external.authSource | b64enc | quote }}
  {{- end }}